adminPassword: admin

rbac:
  create: false
  pspEnabled: false

# Disable test pods
testFramework:
  enabled: false

podLabels:
  app: grafana

podAnnotations:
  "consul.hashicorp.com/connect-inject": "false"

service:
  port: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        orgId: 1
        url: http://prometheus-server.default.svc.cluster.local:80
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 5s
        editable: true
      - name: Jaeger
        type: jaeger
        uid: jaeger-spectra
        access: proxy
        url: http://jaeger-query.default.svc.cluster.local:16686/
        editable: true
        isDefault: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.default.svc.cluster.local:3100/
        editable: true
        isDefault: false