global:
  name: consul
  enabled: false
  datacenter: hcp-learn-fa4wah
  image: "hashicorp/consul-enterprise:1.13.2-ent"
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
  enableConsulNamespaces: true
externalServers:
  enabled: true
  hosts: ["hcp-learn-fa4wah.private.consul.98a0dcc3-5473-4e4d-a28e-6c343c498530.aws.hashicorp.cloud"]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: https://D2A43A4E85FD4CE93AC3494C6A56BBE4.gr7.us-east-1.eks.amazonaws.com
server:
  enabled: false
client:
  enabled: true
  join: ["hcp-learn-fa4wah.private.consul.98a0dcc3-5473-4e4d-a28e-6c343c498530.aws.hashicorp.cloud"]
connectInject:
  enabled: true
controller:
  enabled: true
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
        ports:
          - port: 8080
